#!/bin/bash
# s3md5-commandparms
# 
#   Copyright (C) 2015 
# This file is part of s3md5bu by Russell Gadd <rustleg@gmail.com>
#
# s3md5bu is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
# or see <http://www.gnu.org/licenses/>

#-----------------------------------------------------------------------------------------------

# BUCKET is declared in s3md5-userparms

declare THROTTLE=

# parse command line options
declare OPTION
while [[ $# > 1 ]]
do
	OPTION="$1"
	case $OPTION in
		-b|--bucket)
		BUCKET="$2"
		shift
		;;
		-t|--throttle)
		THROTTLE="trickle -s -u $2"
		shift
		;;
		*)
		echo "******* Unknown option, aborted"
		exit 1
		;;
	esac
	shift # shifts over option specified
done


if [ "${BUCKET}" == "test" ] ; then
	S3MD5ROOT=/data/WorkInProgressSSD/s3dev/s3md5BackupSystemTest # location of this system
fi


