#!/bin/bash
# s3md5-storescripts - updates stored scripts and docs on s3
#
#   Copyright (C) 2015 
# This file is part of s3md5bu by Russell Gadd <rustleg@gmail.com>
#
# s3md5bu is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
# or see <http://www.gnu.org/licenses/>

#-----------------------------------------------------------------------------------------------
#set -x #shows commands being executed on the terminal for debugging purposes

cd /data/s3md5BackupSystem
s3cmd -r --exclude=bu-* --exclude=*~ sync . s3://xxxxxxxxx-backupsoftware/
