#!/bin/bash
# abortmultipart - shows incomplete multipart uploads and offers to remove all parts
# 

source ~/s3md5-userparameters # user needs to set these
source ${S3MD5ROOT}/scripts/sub/s3md5-commandparms # parse command line
source ${S3MD5ROOT}/scripts/sub/s3md5-declares # keep all variable declarations here for use in all progs

s3cmd multipart ${S3PRE}${BUCKET} > ${TMPMULTIPARTS1}

sed -e '1,2d' < ${TMPMULTIPARTS1} > ${TMPMULTIPARTS2}

if [ ! -s ${TMPMULTIPARTS2} ] ; then
	printf "There are no remaining incomplete multiparts\n"
	exit 1
fi

printf "This is the list of multipart files:\n"
cat ${TMPMULTIPARTS2}
printf "\nEach file will now be presented for possible deletion\n"

gawk '
	{
		id = $NF
		filename = ""
		for ( i=2; i<NF; i++ ) # filename may contain spaces
			filename = filename $i
		printf("\nFile: %s  %s\n", filename, id )
		system("s3cmd listmp " filename " " id) # list the parts
		printf("Do you want to delete this file? (y/n):")
		getline choice < "/dev/stdin"
		if ( choice == "y" || choice == "Y" ) {
			printf("File %s is being deleted\n", filename)
			system("s3cmd abortmp " filename " " id)
		}
	} ' ${TMPMULTIPARTS2}

exit 0


