#!/bin/bash
# abortmultipart - shows incomplete multipart uploads and offers to remove all parts
# 
#   Copyright (C) 2015 
# This file is part of s3md5 by Russell Gadd <rustleg@gmail.com>
#
# s3md5 is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
# or see <http://www.gnu.org/licenses/>

#-----------------------------------------------------------------------------------------------

source ~/s3md5-userparameters # user needs to set these
source ${S3MD5ROOT}/scripts/sub/s3md5-commandparms # parse command line
source ${S3MD5ROOT}/scripts/sub/s3md5-declares # keep all variable declarations here for use in all progs

s3cmd multipart ${S3PRE}${BUCKET} > ${TMPMULTIPARTS1}

sed -e '1,2d' < ${TMPMULTIPARTS1} > ${TMPMULTIPARTS2}

if [ ! -s ${TMPMULTIPARTS2} ] ; then
	printf "There are no remaining incomplete multiparts\n"
	exit 1
fi

printf "This is the list of multipart files:\n"
cat ${TMPMULTIPARTS2}
printf "\nEach file will now be presented for possible deletion\n"

gawk '
	{
		id = $NF
		filename = ""
		for ( i=2; i<NF; i++ ) # filename may contain spaces
			filename = filename $i
		printf("\nFile: %s  %s\n", filename, id )
		system("s3cmd listmp " filename " " id) # list the parts
		printf("Do you want to delete this file? (y/n):")
		getline choice < "/dev/stdin"
		if ( choice == "y" || choice == "Y" ) {
			printf("File %s is being deleted\n", filename)
			system("s3cmd abortmp " filename " " id)
		}
	} ' ${TMPMULTIPARTS2}

exit 0


