#!/bin/bash
# s3md5-auditindex
#
#   Copyright (C) 2015 
# This file is part of s3md5bu by Russell Gadd <rustleg@gmail.com>
#
# s3md5bu is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
# or see <http://www.gnu.org/licenses/>

#-----------------------------------------------------------------------------------------------
#set -x #shows commands being executed on the terminal for debugging purposes

source ~/s3md5-userparameters # user needs to set these
source ${S3MD5ROOT}/scripts/sub/s3md5-commandparms # parse command line
source ${S3MD5ROOT}/scripts/sub/s3md5-declares # keep all variable declarations here for use in all progs
source ${S3MD5ROOT}/scripts/sub/s3md5-functions # keep all functions here for use in most progs
source ${S3MD5ROOT}/scripts/sub/s3md5-fns-${CLIENT} # all functions which depend on external s3 client command line package are here

# first check to avoid running a second instance
if [ ! -d ${ISRUNNINGDIRECTORY} ]; then
	mkdir ${ISRUNNINGDIRECTORY}
else
	printf "Another s3md5 program is already running - abort\n"
	exit 1
fi

initialise


#sort index in MD5 order
LC_ALL=C sort ${INDEX} >${INDEXBYMD5}
listfilesbucket # will already be in MD5 order

audit
storeindex

# set +x
rmdir ${ISRUNNINGDIRECTORY}
exit 0


