#!/bin/bash
# s3md5-totalvolume - prints volume of storage used at s3 (according to the indexes)
#
#   Copyright (C) 2015 
# This file is part of s3md5bu by Russell Gadd <rustleg@gmail.com>
#
# s3md5bu is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
# or see <http://www.gnu.org/licenses/>

#-----------------------------------------------------------------------------------------------
#set -x #shows commands being executed on the terminal for debugging purposes

source ~/s3md5-userparameters # user needs to set these
source ${S3MD5ROOT}/scripts/sub/s3md5-declares # keep all variable declarations here for use in all progs

declare DIR
declare INDEXLIST=${TMPDIR}/tmp-totalstorageindexlist.txt
declare TMPSUM=${TMPDIR}/tmp-totalstorage.txt
cat /dev/null > ${TMPSUM}

for DIR in ${S3MD5ROOT}/bu-*/index
do
  # get latest archived index
  ls -1 ${DIR}/*.tsv > ${INDEXLIST} 2>/dev/null
  EXITSTATUS=$?
  if [ $EXITSTATUS -eq 0 ]; then
    LATESTINDEX=$(sort ${INDEXLIST} | tail -1)
  fi
	gawk 'BEGIN { FS = "\t"; OFS = "\t"; size=0; files=0 }
	{ size+= $4 ; files+= $6 }
	END { 
	printf("Index %s : files = %'"'"'d, storage = %'"'"'d MB\n", "'${LATESTINDEX}'", files, size/1000000 )
	printf("%d\t%d\n",files,size) >> "'${TMPSUM}'"
	}
	' ${LATESTINDEX}
done

gawk 'BEGIN { FS = "\t"; size=0; files=0 }
{ files+= $1; size+= $2 }
END { 
printf("\nTotal files =  %'"'"'d,  storage = %'"'"'d MB\n", files, size/1000000 )
} 
' ${TMPSUM}

# set +x


