#!/bin/bash
# s3md5-testexclusions
#
#   Copyright (C) 2015 
# This file is part of s3md5 by Russell Gadd <rustleg@gmail.com>
#
# s3md5 is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
# or see <http://www.gnu.org/licenses/>

#-----------------------------------------------------------------------------------------------

# egrep regular expressions are used in EXCLUDES file
# use this program to check regular expressions are producing the desired results
#
# run, then examine s3md5BackupExluded.txt

source ~/s3md5-userparameters # user needs to set these
source ${S3MD5ROOT}/scripts/sub/s3md5-commandparms # parse command line
source ${S3MD5ROOT}/scripts/sub/s3md5-declares # keep all variable declarations here for use in all progs
source ${S3MD5ROOT}/scripts/sub/s3md5-functions # keep all functions here for use in all progs

initialise
readstate
readbackuproots

exit 0


