#!/bin/bash
# s3md5-totalvolume
# prints volume of storage used at s3 (according to the indexes)
#

#-----------------------------------------------------------------------------------------------
#set -x #shows commands being executed on the terminal for debugging purposes

source ~/s3md5-userparameters # user needs to set these
source ${S3MD5ROOT}/scripts/sub/s3md5-declares # keep all variable declarations here for use in all progs

declare DIR
declare INDEXLIST=${TMPDIR}/tmp-totalstorageindexlist.txt
declare TMPSUM=${TMPDIR}/tmp-totalstorage.txt
cat /dev/null > ${TMPSUM}

for DIR in ${S3MD5ROOT}/bu-*/index
do
  # get latest archived index
  ls -1 ${DIR}/*.tsv > ${INDEXLIST} 2>/dev/null
  EXITSTATUS=$?
  if [ $EXITSTATUS -eq 0 ]; then
    LATESTINDEX=$(sort ${INDEXLIST} | tail -1)
  fi
	gawk 'BEGIN { FS = "\t"; OFS = "\t"; size=0; files=0 }
	{ size+= $4 ; files+= $6 }
	END { 
	printf("Index %s : files = %'"'"'d, storage = %'"'"'d MB\n", "'${LATESTINDEX}'", files, size/1000000 )
	printf("%d\t%d\n",files,size) >> "'${TMPSUM}'"
	}
	' ${LATESTINDEX}
done

gawk 'BEGIN { FS = "\t"; size=0; files=0 }
{ files+= $1; size+= $2 }
END { 
printf("\nTotal files =  %'"'"'d,  storage = %'"'"'d MB\n", files, size/1000000 )
} 
' ${TMPSUM}

# set +x


